# SERVICIOS-MUNICIPALES/docker-compose.override.yml
version: '3.8'

services:
  backend:
    ports:
      - "${SM_BACKEND_HOST_PORT:-3001}:${SM_BACKEND_INTERNAL_PORT:-3001}"
    volumes:
      - ./backend:/app
      - /app/node_modules
    environment:
      NODE_ENV: development
    command: npm run server

  frontend:
    ports:
      - "${SM_FRONTEND_HOST_PORT:-8080}:${SM_FRONTEND_INTERNAL_PORT:-8080}"
