# SERVICIOS-MUNICIPALES/docker-compose.yml
# Configuración base ACTUALIZADA para el servidor (CON puerto DB expuesto a localhost)

version: '3.8'

services:
  db:
    image: mysql:8.0
    container_name: mysql_servicios_municipales
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${SM_DB_ROOT_PASSWORD}
      MYSQL_DATABASE: ${SM_DB_DATABASE}
      MYSQL_USER: ${SM_DB_USER}
      MYSQL_PASSWORD: ${SM_DB_PASSWORD}
    volumes:
      - mysql_servicios_data:/var/lib/mysql
    ports:
      - "${SM_DB_PORT:-3306}:3306" # Solo accesible desde localhost
    networks:
      - servicios_municipales_net

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: backend_servicios_municipales
    restart: always
    environment:
      NODE_ENV: ${NODE_ENV:-production}
      PORT: ${SM_BACKEND_INTERNAL_PORT}
      DB_HOST: db
      DB_PORT: 3306
      DB_USER: ${SM_DB_USER}
      DB_PASSWORD: ${SM_DB_PASSWORD}
      DB_NAME: ${SM_DB_DATABASE}
      JWT_SECRET: ${SM_JWT_SECRET}
      JWT_EXPIRES_IN: ${SM_JWT_EXPIRES_IN}
      CLAVEUNICA_CLIENT_ID: ${SM_CLAVEUNICA_CLIENT_ID}
      CLAVEUNICA_CLIENT_SECRET: ${SM_CLAVEUNICA_CLIENT_SECRET}
      CLAVEUNICA_REDIRECT_URI: ${SM_CLAVEUNICA_REDIRECT_URI}
      CLAVEUNICA_AUTH_URL: ${SM_CLAVEUNICA_AUTH_URL}
      CLAVEUNICA_TOKEN_URL: ${SM_CLAVEUNICA_TOKEN_URL}
      CLAVEUNICA_USERINFO_URL: ${SM_CLAVEUNICA_USERINFO_URL}
      EMAIL_USER: ${SM_EMAIL_USER}
      EMAIL_PASS: ${SM_EMAIL_PASS}
      EMAIL_HOST: ${SM_EMAIL_HOST}
      EMAIL_PORT: ${SM_EMAIL_PORT}
      EMAIL_SECURE: ${SM_EMAIL_SECURE}
    depends_on:
      - db
    networks:
      - servicios_municipales_net

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
      args:
        SM_REACT_APP_API_URL: ${SM_REACT_APP_API_URL:-http://localhost:${SM_BACKEND_HOST_PORT}/api}
    container_name: frontend_servicios_municipales
    restart: always
    networks:
      - servicios_municipales_net

volumes:
  mysql_servicios_data:
    name: mysql_servicios_data

networks:
  servicios_municipales_net:
    name: servicios_municipales_net
    driver: bridge
